<?php
  // The one page on the site rendered by PHP instead of React - it reads
  // the server's own clock on every request, which is the whole point:
  // refresh and the timestamp changes, proving this isn't a static file.
  date_default_timezone_set('Africa/Kigali');
  $now = date('l, d F Y - H:i:s');
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Server Time - Fundi</title>
<link rel="stylesheet" href="style.css">
<link rel="icon" type="image/svg+xml" href="favicon.svg">
<link rel="alternate icon" href="favicon.png">
</head>
<body>
<header>
  <div class="brand-row">
    <a href="index.html" class="logo"><img src="brand/fundi-logo.png" alt="Fundi" class="logo-mark"></a>
    <nav aria-label="Main navigation">
      <ul>
        <!-- This page sits outside the React app, so these are plain links
             (full page loads) back into the SPA's hash routes. -->
        <li><a href="index.html#/">Home</a></li>
        <li><a href="index.html#/about">About</a></li>
        <li><a href="index.html#/contact">Contact</a></li>
        <li><a href="index.html#/register">Become a fundi</a></li>
        <li><a href="index.html#/login">Login</a></li>
      </ul>
    </nav>
  </div>
</header>

<main>
  <section class="card">
    <h2>Current server date &amp; time</h2>
    <p>It is currently: <strong><?php echo htmlspecialchars($now); ?></strong> (Africa/Kigali time).</p>
    <p class="muted">This page is generated by PHP on every request - refresh to see the time change, which confirms it is server-rendered rather than static HTML or a React component.</p>
  </section>
</main>

<footer>
  <div class="footer-row">
    <a href="index.html" class="logo"><img src="brand/fundi-logo.png" alt="Fundi" class="logo-mark"></a>
    <p><a href="server-time.php">Server time</a> &nbsp;&middot;&nbsp; &copy; 2026 Fundi. Kigali, Rwanda.</p>
  </div>
</footer>
</body>
</html>
